### ISSUE TITLE
Set up issue

### ISSUE THREAD

**Issue by Deepakmukka1** [akshay782/venue_booking_site#3]
When i run the project(both backend and frontend) i got this issue

![image](https://user-images.githubusercontent.com/56472120/176383468-ea02c36b-9f77-4f38-aca3-7eebce79fae7.png)

**Comment by kanadeakshay** [comment]
Hi Deepak,
I run the project on my side and it is working completely fine
![ss](https://user-images.githubusercontent.com/68458601/176407888-447d204d-1faa-4d8a-8796-9e9063067136.png)

You can start by checking if there is any issue in your redux store or client-side\src\reducers\auth.reducers.js

When you first try to run the project it should run, while trying to log in maybe you are getting this error (my guess)
For this, you can check if the conditional rendering is working or not in file client-side\src\components\Layout\index.layout.js

**Comment by kanadeakshay** [comment]
@Deepakmukka1
Did your problem gets solved?
I will properly update the README.md later.
If your problem is resolved let me know. I will close this issue.

**Comment by Deepakmukka1** [comment]
> Hi Deepak, I run the project on my side and it is working completely fine ![ss](https://user-images.githubusercontent.com/68458601/176407888-447d204d-1faa-4d8a-8796-9e9063067136.png)
> 
> You can start by checking if there is any issue in your redux store or client-side\src\reducers\auth.reducers.js
> 
> When you first try to run the project it should run, while trying to log in maybe you are getting this error (my guess) For this, you can check if the conditional rendering is working or not in file client-side\src\components\Layout\index.layout.js

I haven't been much into redux, i recently started learning redux, will run the project again and let you know
